// Command gen-lang-maps regenerates the language package's ISO 639-3
// lookup tables from the SIL reference data:
//
//   - iso6393names.go — ISO 639-3 code → English language name
//   - iso6393macro.go — individual language code → macrolanguage code
//
// It downloads the current SIL ISO 639-3 ".tab" files directly. Those
// URLs always serve the latest release, so the generator does not go
// stale the way the previously used date-stamped Code_Tables ZIP did
// (that ZIP endpoint is now also blocked by the site's CDN).
//
// Regenerate the tables with:
//
//	go generate ./language/...
//
// or by running this command from any directory:
//
//	go run ./language/gen-lang-maps
//
// Output files are located relative to this command's own source path,
// so the working directory does not matter.
//
// Data source: https://iso639-3.sil.org/code_tables/download_tables
package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"go/format"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
)

// SIL ISO 639-3 reference files. These un-dated URLs always point at
// the most recent release of each table.
const (
	nameIndexURL      = "https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Name_Index.tab"
	macrolanguagesURL = "https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab"
)

const namesHeader = `// Code generated by language/gen-lang-maps. DO NOT EDIT.

package language

// iso6393Names maps every ISO 639-3 three-letter code to the English
// reference name of its language, taken from the SIL ISO 639-3 Name
// Index. A code with several recorded names keeps the first (primary)
// name as the live entry; the alternate names follow on commented-out
// lines for reference.
//
// Use the exported ISO6393Name function to query this map.
var iso6393Names = map[string]string{
`

const macroHeader = `// Code generated by language/gen-lang-maps. DO NOT EDIT.

package language

// iso6393Macro maps an ISO 639-3 individual language code to the
// ISO 639-3 macrolanguage code that encompasses it, taken from the
// SIL ISO 639-3 macrolanguage mappings. Mappings that the source data
// marks as retired are kept on commented-out lines for reference.
//
// Use the exported ISO6393Macrolanguage function to query this map.
var iso6393Macro = map[string]string{
`

//go:generate go run .

func main() {
	log.SetFlags(0)

	_, genFile, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("cannot determine generator source path")
	}
	// genFile is .../language/gen-lang-maps/gen-lang-maps.go,
	// so the language package directory is two levels up.
	langDir := filepath.Dir(filepath.Dir(genFile))

	writeGoFile(filepath.Join(langDir, "iso6393names.go"), genNames(fetchTSV(nameIndexURL)))
	writeGoFile(filepath.Join(langDir, "iso6393macro.go"), genMacro(fetchTSV(macrolanguagesURL)))
}

// fetchTSV downloads a tab-separated SIL table and returns its data
// rows (the header row is dropped).
func fetchTSV(url string) [][]string {
	log.Println("downloading", url)
	req, err := http.NewRequest(http.MethodGet, url, nil) //#nosec G107 -- url is a package-level constant
	if err != nil {
		log.Fatalf("building request for %s: %v", url, err)
	}
	// The SIL site's CDN rejects the default Go User-Agent with 403.
	req.Header.Set("User-Agent", "Mozilla/5.0 (compatible; go-types/gen-lang-maps)")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		log.Fatalf("downloading %s: %v", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("downloading %s: unexpected status %s", url, resp.Status)
	}

	reader := csv.NewReader(resp.Body)
	reader.Comma = '\t'
	reader.LazyQuotes = true // language names are plain text, never quoted fields
	rows, err := reader.ReadAll()
	if err != nil {
		log.Fatalf("parsing %s: %v", url, err)
	}
	if len(rows) < 2 {
		log.Fatalf("%s: expected a header and at least one data row, got %d row(s)", url, len(rows))
	}
	return rows[1:]
}

// genNames builds the source of iso6393names.go from the Name Index
// rows (Id, Print_Name, Inverted_Name).
func genNames(rows [][]string) []byte {
	sort.SliceStable(rows, func(i, j int) bool { return rows[i][0] < rows[j][0] })

	var buf bytes.Buffer
	buf.WriteString(namesHeader)
	seen := make(map[string]bool, len(rows))
	for _, row := range rows {
		id, name := row[0], row[1]
		if seen[id] {
			// An alternate name for an already-emitted code:
			// keep it as a comment so the map stays unique.
			fmt.Fprintf(&buf, "// %q: %q,\n", id, name)
			continue
		}
		fmt.Fprintf(&buf, "%q: %q,\n", id, name)
		seen[id] = true
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

// genMacro builds the source of iso6393macro.go from the macrolanguage
// rows (M_Id, I_Id, I_Status).
func genMacro(rows [][]string) []byte {
	sort.SliceStable(rows, func(i, j int) bool { return rows[i][1] < rows[j][1] })

	var buf bytes.Buffer
	buf.WriteString(macroHeader)
	for _, row := range rows {
		macro, individual, status := row[0], row[1], row[2]
		switch status {
		case "A":
			fmt.Fprintf(&buf, "%q: %q,\n", individual, macro)
		case "R":
			// Retired mapping: kept as a comment for reference.
			fmt.Fprintf(&buf, "// %q: %q,\n", individual, macro)
		default:
			log.Fatalf("unexpected I_Status %q for individual code %q", status, individual)
		}
	}
	buf.WriteString("}\n")
	return buf.Bytes()
}

// writeGoFile gofmt-formats src and writes it to path.
func writeGoFile(path string, src []byte) {
	formatted, err := format.Source(src)
	if err != nil {
		log.Fatalf("formatting %s: %v", path, err)
	}
	// 0644: generated Go source, world-readable like its siblings.
	err = os.WriteFile(path, formatted, 0644) //#nosec G306
	if err != nil {
		log.Fatalf("writing %s: %v", path, err)
	}
	log.Println("wrote", path)
}
